[package]
name = "glibc-rs-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Safe Rust implementations of libc functions"

[lints.rust]
unsafe_code = "deny"

[dependencies]
glibc-rs-membrane = { workspace = true }
